version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment: 
      PORT: "3000"
      HOST: "http://localhost:3000"
      MONGODB_URI: "mongodb://mongo:27017/example"
      JWT_SECRET: "secret"
    depends_on:
      - mongo
    command: npm run dev
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo